import streamlit as st
import pandas as pd
from datetime import datetime
from auth import login_user, logout_user, check_auth, get_logged_in_user, get_credentials
from google_manager import GoogleManager

# --- Page Configuration ---
st.set_page_config(page_title="Good Will Hunt", page_icon="🎯", layout="wide")

# --- Authentication (Manual Handshake) ---
is_logged_in = check_auth()

if not is_logged_in:
    st.title("🎯 Good Will Hunt: AI Job Hunter")
    st.markdown("Automate job hunting: track positions, analyze fit, and generate tailored resumes.")
    st.info("Please login with your Google account to get started.")
    login_user() 
    st.stop()

# --- Initialize Google Manager & DB ---
creds = get_credentials()
gm = GoogleManager(creds)

if "spreadsheet_id" not in st.session_state:
    spreadsheet_id = gm.find_or_create_db()
    st.session_state["spreadsheet_id"] = spreadsheet_id
    # Force a rerun to sync UI after creation/find
    st.rerun()

spreadsheet_id = st.session_state["spreadsheet_id"]

# --- Header / User Info ---
user = get_logged_in_user()
col_title, col_user = st.columns([4, 1])

with col_title:
    st.title("🎯 Good Will Hunt: AI Job Hunter")

with col_user:
    if user:
        c1, c2 = st.columns([1, 2])
        with c1:
            st.image(user.get("picture", ""), width=40)
        with c2:
            st.caption(f"**{user.get('name', 'User')}**")
            if st.button("Logout"):
                logout_user()

st.divider()

# --- UI Layout: Two Main Tabs ---
tab_tracker, tab_profiles = st.tabs(["📊 Jobs Tracker (Review)", "📋 Job Profiles (Settings)"])

# TAB 1: Tracker
with tab_tracker:
    st.header("Pending Job Applications")
    st.info("Review the jobs and tailored resumes generated by the AI Agent.")
    
    # LOAD LIVE DATA
    df_tracker = gm.load_sheet_data(spreadsheet_id, "Jobs Tracker")
    
    st.subheader("Action Dashboard")
    
    if not df_tracker.empty:
        # Match Score needs to be numeric for progress column
        if "Match Score" in df_tracker.columns:
            df_tracker["Match Score"] = pd.to_numeric(df_tracker["Match Score"], errors="coerce").fillna(0)

        edited_tracker = st.data_editor(
            df_tracker,
            column_config={
                "Match Score": st.column_config.ProgressColumn(
                    "Match Score", format="%d", min_value=0, max_value=100
                ),
                "Resume URL": st.column_config.LinkColumn("Tailored Resume Link"),
                "Status": st.column_config.SelectboxColumn(
                    "Status", options=["Pending", "Applied", "Interview", "Rejected", "Archived"], required=True
                )
            },
            hide_index=True,
            use_container_width=True,
            key="tracker_editor"
        )
        
        if st.button("💾 Save Changes to Database", type="primary"):
            gm.sync_data(spreadsheet_id, "Jobs Tracker", edited_tracker)
            st.success("Success! Changes synced to Google Sheets.")
            st.rerun()
    else:
        st.warning("No data found in Jobs Tracker. The Agent will populate this once it starts running.")

# TAB 2: Profiles
with tab_profiles:
    st.header("Search Strategy Configuration")
    
    # LOAD LIVE DATA
    df_profiles = gm.load_sheet_data(spreadsheet_id, "Job Profiles")

    with st.expander("➕ Add New Job Profile", expanded=False):
        with st.form("new_profile_form"):
            col1, col2 = st.columns(2)
            with col1:
                new_title = st.text_input("Target Job Title", placeholder="e.g., Python Developer")
            with col2:
                new_location = st.text_input("Location / Work Type", placeholder="e.g., Remote, NY")
            new_keywords = st.text_input("Mandatory Keywords (comma separated)", placeholder="e.g., LangChain, API")
            submit_profile = st.form_submit_button("Save Profile")
            
            if submit_profile:
                if new_title:
                    # Append new profile to existing data
                    new_row = pd.DataFrame({
                        "Profile ID": [f"PROF-{datetime.now().strftime('%M%S')}"],
                        "Title": [new_title],
                        "Location": [new_location],
                        "Keywords": [new_keywords],
                        "Status": ["Active"]
                    })
                    updated_profiles = pd.concat([df_profiles, new_row], ignore_index=True)
                    gm.sync_data(spreadsheet_id, "Job Profiles", updated_profiles)
                    st.success(f"Profile saved: {new_title}")
                    st.rerun()
                else:
                    st.error("Please provide at least a Target Job Title.")

    st.subheader("Current Profiles")
    if not df_profiles.empty:
        edited_profiles = st.data_editor(
            df_profiles,
            column_config={
                "Status": st.column_config.SelectboxColumn("Status", options=["Active", "Paused", "Deleted"], required=True)
            },
            hide_index=True,
            use_container_width=True,
            key="profiles_editor"
        )
        
        if st.button("💾 Update Profiles", key="update_profiles"):
            gm.sync_data(spreadsheet_id, "Job Profiles", edited_profiles)
            st.success("Profiles updated.")
            st.rerun()
    else:
        st.info("No job profiles defined yet. Add one above to start.")
